# Generated by Django 4.1.7 on 2023-12-04 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='price',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(0)]),
        ),
    ]
